export const strings = {
    music:"Music",
    gaming:"Gaming",
    like:"Like",
    shares:"Shares",
    gift:"Gift",
    news:"News",
    share:"Share",
    movies:"Movies",
    fashion:"Fashion",
    recentStories:"Recent Stories",
    watchAll:"Watch All",
    subScribe:"Subscribe",
    home:"Home",
    trending:"Trending",
    subscription:"FOLLOW",
    subscribe:"Subscribe",
    post:"Post",
    promote:"Promote",
    save:"Save",
    view:"Views",
    nextVideos:"Next videos",
    appName:'𝐆𝐮𝐫𝐮𝐀𝐩𝐩',
    //𝙶𝚞𝚛𝚞𝙰𝚙𝚙
    mail:'Enter Your Email',
    pass:'Enter Your Password',
    login:'Log In',
    forgotPassText:'Forgot Login Details?',
    forgotPassLink:'Get Help',
    dontHaveAccount:"Don't have an account?",
    signUp:'Sign Up',
    fbLogin:'Facebook',
    googleLogin:'Google',
    otpMsg:"You will receive an OTP on your phone to verfiy your Mobile Number",
    fbLogin:'Log in with Facebook',
    googleLogin:'Log in with Google',
    dateOfBirth:"Date of Birth",
    invalidEmail:'Please enter correct email',
    invalidPassword:'Password must be atleast six character long and contain one special character and one numeric',
    globalErrorMsg:'Something went wrong',
    serverFailedMsg:"Server Failed Please Try again later",
    noVideosFound:"No Video's found for this category",
    privacySafety:"Privacy and Safety",
    editProfile:"Edit Profile",
    followers:"Followers",
    following:"Following",
    balance:"Balance",
    paymentMode:"Select your Payment Mode",
    transactions:'Transactions',
    editProfile:'Edit Profile'
    }